export const EXCEPTION_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_JSON: "INVALID_JSON",
  INVALID_PARAMETER: "INVALID_PARAMETER",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ExceptionCode = (typeof EXCEPTION_CODES)[keyof typeof EXCEPTION_CODES];
